version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: btg-rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    mem_limit: 300m

  postgres:
    image: postgres:15-alpine
    container_name: btg-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btg_cards_db
    mem_limit: 300m

  mongodb:
    image: mongo:6.0
    container_name: btg-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    mem_limit: 400m

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: btg-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m 
    ports:
      - "9200:9200"
    mem_limit: 800m